homebrew_cask_apps:
  # Base cask apps
  - font-hack-nerd-font
  - firefox
  - google-chrome
  - iterm2
  - vscodium
  - postman
  - spotify
  # Personal cask apps
  - docker
  - teamviewer
  - private-internet-access

homebrew_cask_uninstalled_apps: []

mas_installed_apps: 
  # Base mas apps
  - { id: 926036361,  name: "LastPass Password Manager" }
  - { id: 1451685025, name: "WireGuard" }
  - { id: 417375580, name: "BetterSnapTool" }
  #- { id: 497799835, name: "Xcode" }
  # Personal mas apps
  - { id: 571213070, name: "DaVinci Resolve" }
  - { id: 823766827, name: "OneDrive" }
  

mas_uninstalled_apps:
  # Base mas apps
  - { id: 408981434, name: "iMovie" }
  - { id: 409183694, name: "Keynote" }
  - { id: 409201541, name: "Pages" }
  - { id: 409203825, name: "Numbers" }
  - { id: 682658836, name: "GarageBand" }
